In [1]:
import util, lines, group

In [2]:
# path to pdf file with three identation types
file_path = "../test_files/LS_index_1920.pdf"

# read pdf with fitz
pdf_words, pdf_dicts = util.read_pdf(file_path)

Reading pdf from ../test_files/LS_index_1920.pdf
...
Finished reading 11 page(s)

In [3]:
# make lines data frame
words_df = lines.make_words_df(pdf_words, start_page=1)
lines_df = words_df.rename(columns={"text": "line_text"})
lines_df["x0"] = [round(x, 2) for x in lines_df["x0"]]
lines_df["y0"] = [round(x, 2) for x in lines_df["y0"]]
lines_df["x1"] = [round(x, 2) for x in lines_df["x1"]]
lines_df["y1"] = [round(x, 2) for x in lines_df["y1"]]
lines_df = lines.merge_close_lines(lines_df)
lines_df = lines.remove_useless_lines(lines_df)

lines_df

,line_text,spans,x0,y0,x1,y1,page
0,I. CHRONOLOGICAL INDEX OF LAWS AND ORDERS IN,"[I., CHRONOLOGICAL, INDEX, OF, LAWS, AND, ORDE...",48.0,78.66,351.96,90.66,1
1,THE ENGLISH EDITION OF THE LEGISLATiVE,"[THE, ENGLISH, EDITION, OF, THE, LEGISLATiVE]",75.0,91.03,351.87,104.13,1
2,SERIES OF THE INTERNATIONAL LABOUR,"[SERIES, OF, THE, INTERNATIONAL, LABOUR]",77.0,105.66,350.81,116.86,1
3,"OFFICE, 1920.","[OFFICE,, 1920.]",76.0,118.41,146.62,129.81,1
4,"Nora.—T. E., S., or Ti. after the title of a l...","[Nora.—T., E.,, S.,, or, Ti., after, the, titl...",63.0,147.96,350.17,157.96,1
...,...,...,...,...,...,...,...
761,Decree to include messengers under the Eight-H...,"[Decree, to, include, messengers, under, the, ...",68.0,511.51,327.87,522.03,11
762,"October, 1920. T., Ur. 3—5 ..","[October,, 1920., T.,, Ur., 3—5, ..]",85.0,520.81,225.06,531.55,11
765,. Act respecting occupational accidents. 15th ...,"[., Act, respecting, occupational, accidents.,...",68.0,526.76,330.57,537.86,11
766,Ur.r .. .. .. .. .. .. .. ..,"[Ur.r, .., .., .., .., .., .., .., ..]",85.0,535.33,301.28,546.43,11
767,"Act concerning weekly rest. 22nd November, 192...","[Act, concerning, weekly, rest., 22nd, Novembe...",67.0,544.01,310.48,553.93,11

In [4]:
# filter lines from one specified page for demonstration purposes
page = 3
df = lines_df.loc[lines_df["page"]==page]

df

,line_text,spans,x0,y0,x1,y1,page
134,4,[4],205.0,21.79,208.10,27.99,3
135,AUsTRIA—Continued.,[AUsTRIA—Continued.],63.0,27.44,139.66,35.44,3
136,Order of the Federal Department for Social Adm...,"[Order, of, the, Federal, Department, for, Soc...",80.0,36.94,341.06,46.94,3
137,"the Acts of 26th February, 5920, and 1st Octob...","[the, Acts, of, 26th, February,, 5920,, and, 1...",97.0,45.49,339.73,54.89,3
138,the establishment of labour councils. 10th Nov...,"[the, establishment, of, labour, councils., 10...",97.0,53.04,340.39,63.04,3
...,...,...,...,...,...,...,...
196,Act respecting compulsory labour service. 5th ...,"[Act, respecting, compulsory, labour, service....",80.0,549.87,338.82,559.17,3
197,COLOMBIA.,[COLOMBIA.],63.0,565.27,102.45,572.37,3
198,Act No. 21 of 1920 respecting conciliation and...,"[Act, No., 21, of, 1920, respecting, conciliat...",80.0,574.94,340.88,584.14,3
199,"labour disputes, supplementing Act No. 78 of 1...","[labour, disputes,, supplementing, Act, No., 7...",97.0,582.52,342.83,592.41,3
200,"strikes. 4th October, 1920. T., Col.","[strikes., 4th, October,, 1920., T.,, Col.]",97.0,591.24,238.20,600.44,3

In [5]:
# group lines based on their x0-coordinate
x0_groups = group.group_rows(df, by="x0", mode="fitz")

# sort groups by mean x0 value
x0_groups = x0_groups.sort_values(by="last_x0_mean")

x0_groups

,x0,lines,last_x0,last_x0_mean,count
2,"[63.0, 63.0, 63.0, 64.0, 64.0, 63.0]","[135, 140, 187, 189, 195, 197]","[64.0, 63.0]",63.5,6
1,"[80.0, 81.0, 80.0, 81.0, 80.0, 81.0, 80.0, 80....","[136, 141, 142, 145, 151, 154, 157, 159, 163, ...","[80.0, 80.0]",80.0,21
0,"[97.0, 97.0, 97.0, 97.0, 98.0, 97.0, 97.0, 97....","[137, 138, 139, 143, 144, 146, 147, 148, 149, ...","[97.0, 97.0]",97.0,37
3,[205.0],[134],[205.0],205.0,1

In [6]:
# get lines in first group -> countries
df.loc[x0_groups.iloc[0]["lines"]]

,line_text,spans,x0,y0,x1,y1,page
135,AUsTRIA—Continued.,[AUsTRIA—Continued.],63.0,27.44,139.66,35.44,3
140,BELGIUM.,[BELGIUM.],63.0,78.96,98.84,86.46,3
187,BOLIVIA.,[BOLIVIA.],63.0,457.49,95.26,464.89,3
189,BRAZIL.,[BRAZIL.],64.0,482.76,92.19,490.07,3
195,BULGARIA.,[BULGARIA.],64.0,540.14,103.48,547.54,3
197,COLOMBIA.,[COLOMBIA.],63.0,565.27,102.45,572.37,3

In [7]:
# get lines in second group -> start of entries
df.loc[x0_groups.iloc[1]["lines"]]

,line_text,spans,x0,y0,x1,y1,page
136,Order of the Federal Department for Social Adm...,"[Order, of, the, Federal, Department, for, Soc...",80.0,36.94,341.06,46.94,3
141,Royal Order instituting an Industrial Medical ...,"[Royal, Order, instituting, an, Industrial, Me...",81.0,87.94,340.00,98.27,3
142,"1919. T., Bel. 1—3 . . . . Ministerial Order i...","[1919., T.,, Bel., 1—3, ., ., ., ., Ministeria...",80.0,97.54,339.43,114.19,3
145,Royal Order defining the to be taken by the in...,"[Royal, Order, defining, the, to, be, taken, b...",81.0,128.82,340.32,138.39,3
151,Royal Decree respecting electrical plant in co...,"[Royal, Decree, respecting, electrical, plant,...",80.0,176.72,341.52,186.62,3
154,. . Royal Order respecting surface works in co...,"[., ., Royal, Order, respecting, surface, work...",81.0,198.24,341.08,210.67,3
157,Royal Order : Institution of a staff of labour...,"[Royal, Order, :, Institution, of, a, staff, o...",80.0,224.69,340.36,234.89,3
159,". Royal Orders Dangerous, unhealthy or noxious...","[., Royal, Orders, Dangerous,, unhealthy, or, ...",80.0,240.24,335.79,250.96,3
163,"Royal Order Dangerous, unhealthy or noxious un...","[Royal, Order, Dangerous,, unhealthy, or, noxi...",81.0,273.07,335.56,283.17,3
167,Royal Order defining the action to be taken by...,"[Royal, Order, defining, the, action, to, be, ...",81.0,305.59,341.28,314.99,3
172,Royal Order organising a system for supervisin...,"[Royal, Order, organising, a, system, for, sup...",80.0,345.34,340.85,355.34,3
177,"Royal Order : Dangerous, unhealthy and noxious...","[Royal, Order, :, Dangerous,, unhealthy, and, ...",80.0,369.34,336.03,379.34,3
180,Royal Order providing for the supervision of t...,"[Royal, Order, providing, for, the, supervisio...",80.0,393.64,339.41,403.64,3
182,"Act respecting old age pensions. soth August, ...","[Act, respecting, old, age, pensions., soth, A...",81.0,409.94,323.65,419.54,3
183,Royal Decree promulgating the co-ordinated Act...,"[Royal, Decree, promulgating, the, co-ordinate...",81.0,418.02,341.94,427.52,3
185,Royal Decree respecting the administration of ...,"[Royal, Decree, respecting, the, administratio...",81.0,433.64,342.62,443.64,3
188,"Decree to regulate strikes. 29th September, 19...","[Decree, to, regulate, strikes., 29th, Septemb...",80.0,467.14,306.37,476.74,3
190,Decree respecting liability for industrial acc...,"[Decree, respecting, liability, for, industria...",81.0,492.09,340.80,502.09,3
192,Decree confirming the administrative regulatio...,"[Decree, confirming, the, administrative, regu...",81.0,508.19,342.72,517.99,3
196,Act respecting compulsory labour service. 5th ...,"[Act, respecting, compulsory, labour, service....",80.0,549.87,338.82,559.17,3
198,Act No. 21 of 1920 respecting conciliation and...,"[Act, No., 21, of, 1920, respecting, conciliat...",80.0,574.94,340.88,584.14,3